-- Supabase setup for the chat website
-- Run this entire script in Supabase SQL Editor.

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender text not null,
  message text not null,
  reply_to bigint null,
  created_at timestamptz not null default now(),
  constraint messages_reply_to_fkey
    foreign key (reply_to)
    references public.messages(id)
    on delete set null
);

-- If the table already existed, make sure reply_to is present.
alter table public.messages
  add column if not exists reply_to bigint;

-- Add the foreign key only if it is not already present.
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'messages_reply_to_fkey'
      and conrelid = 'public.messages'::regclass
  ) then
    alter table public.messages
      add constraint messages_reply_to_fkey
      foreign key (reply_to)
      references public.messages(id)
      on delete set null;
  end if;
end $$;

alter table public.messages enable row level security;

drop policy if exists "Anyone can read messages" on public.messages;
create policy "Anyone can read messages"
on public.messages
for select
to anon, authenticated
using (true);

drop policy if exists "Anyone can send messages" on public.messages;
create policy "Anyone can send messages"
on public.messages
for insert
to anon, authenticated
with check (true);

drop policy if exists "Anyone can delete messages" on public.messages;
create policy "Anyone can delete messages"
on public.messages
for delete
to anon, authenticated
using (true);

-- Enable Realtime only if messages is not already in supabase_realtime.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'messages'
  ) then
    alter publication supabase_realtime add table public.messages;
  end if;
end $$;
